events {}

http {
  server {
    listen 8888;

    location /.netlify/functions/ {
      proxy_pass http://functions:9999/;
      proxy_set_header Origin http://localhost:8888;
    }

    location / {
      proxy_pass http://jekyll:4000;
    }
  }
}
